
/** 회원가입 시 User 정보를 저장하기 위한 테이블 */
CREATE TABLE Delievery_Service.USER_BASE(
  PID_NUM       INT(10)       NOT NULL AUTO_INCREMENT,
  STATUS        VARCHAR(10)   NOT NULL DEFAULT 'DEFAULT',
  ID            VARCHAR(20)   NOT NULL,
  PASSWORD      VARCHAR(100)  NOT NULL,
  MOBILE_NUM    VARCHAR(15)   NOT NULL,
  NAME          VARCHAR(10)   DEFAULT NULL,
  BIRTHDATE     DATETIME      DEFAULT NULL,
  DATE_CREATION DATETIME DEFAULT NOW(),
  DATE_UPDATE   DATETIME,
  PRIMARY KEY (PID_NUM)
);